Repository UMC-Edison/Edison-Server, pull requests merged in 2025-06, with the labels that each got.

#198 🚧 [REFACTOR] #197: 에디터픽 아트레터 조회
  project/src/main/java/com/edison/project/domain/artletter/controller/ArtletterController.java
  project/src/main/java/com/edison/project/domain/artletter/entity/EditorPick.java
  project/src/main/java/com/edison/project/domain/artletter/repository/EditorPickRepository.java
  project/src/main/java/com/edison/project/domain/artletter/service/ArtletterService.java
  project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java
Labels: :hammer: refactor

#202 [BUG] space localIdx로 반환하도록 오류 수정, closed #201
  project/src/main/java/com/edison/project/domain/artletter/service/ArtletterServiceImpl.java
  project/src/main/java/com/edison/project/domain/space/controller/SpaceController.java
  project/src/main/java/com/edison/project/domain/space/entity/Space.java
  project/src/main/java/com/edison/project/domain/space/repository/SpaceRepository.java
  project/src/main/java/com/edison/project/domain/space/service/SpaceService.java
  project/src/main/java/com/edison/project/domain/space/service/SpaceServiceImpl.java
  project/src/main/resources/application.properties
Labels: :bug: bug

#204 [BUG] ai 서버 관련 conf 파일 수정 및 route53 세팅 수정
  nginx/nginx.conf
Labels: :bug: bug, :earth_asia: deploy, 👷🏻‍♀️ ci/cd
